id: A8F5E8B4F
base_file: f969D.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-26 14:19:23.971641
  last_modified_at: 2022-06-26 14:19:23.971648
