id: A8F5E8B4F
base_file: f5A98.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-06-26 14:19:23.912035
  last_modified_at: 2022-06-26 14:19:23.912039
