id: A8F5E8B4F
base_file: fD6CA.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  datatype: PlainText
  created_at: 2022-06-26 14:19:23.977472
  last_modified_at: 2022-06-26 14:19:23.977477
