id: A8F5E8B4F
base_file: f8346.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - pt
  datatype: PlainText
  created_at: 2022-06-26 14:19:23.959581
  last_modified_at: 2022-06-26 14:19:23.959586
